FROM alpine

RUN apk add git \
        && apk add yarn \
        && git clone https://github.com/zzzhyrov/docker-example.git \
        && cd docker-example \
        && yarn
        
WORKDIR /docker-example/

EXPOSE 3000

CMD yarn start